version: "3.8"
services:
#  db:

  backend:
    build:
      context: dockerfiles
      dockerfile: jdk.dockerfile
    ports:
      - "8080:8080"
    volumes:
    - ./backend:/app/backend

  angular:
    build:
      context: frontend
      dockerfile: angular.dockerfile
    ports:
    - "4200:4200"
    volumes:
    - ./frontend:/app
    #      - ./frontend/frontend/src:/app/frontend/src

  nginx:
    build:
      context: frontend
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
    - ./frontend/frontend:/usr/share/nginx/html
    - ./frontend/nginx.conf:/etc/nginx/nginx.conf
